#!/usr/bin/env python3
"""Build the mock screenshots' message text and buttons with the plugin's own builders, offline.

Run through docs/demo/render.sh, which gives it an empty environment, a temp HOME and TMPDIR, and a fixture
git repo (origin github.com/example/acme-web). Calls only message builders: nothing is sent, no token is read,
and no real session, workspace or chat data can reach the output. Prints messages.js for mock.html.
"""
import importlib
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "plugins", "telegram-hook",
                                "scripts"))
ask = importlib.import_module("tg-ask")
bot = ask.bot

repo = sys.argv[1]  # fixture checkout
transcript = os.path.join(repo, "..", "transcript.jsonl")
with open(transcript, "w") as f:
    f.write(json.dumps({"type": "ai-title", "aiTitle": "Prepare the 2.4 release"}) + "\n")
base = {"cwd": repo, "transcript_path": transcript, "session_id": "demo"}

question = {**base, "hook_event_name": "PreToolUse", "tool_name": "AskUserQuestion", "tool_input": {"questions": [{
    "question": "Which checks should run before the release?", "multiSelect": True, "options": [
        {"label": "Unit tests", "description": "npm test, about 2 minutes"},
        {"label": "Lint", "description": "eslint and type check"},
        {"label": "End-to-end tests", "description": "Playwright against staging, about 15 minutes"}]}]}}

permission = {**base, "hook_event_name": "PermissionRequest", "tool_name": "Bash",
              "tool_input": {"command": "npm run test:e2e -- --project=staging",
                             "description": "Run the end-to-end suite against staging"},
              "permission_suggestions": [{"type": "addRules", "behavior": "allow", "destination": "localSettings",
                                          "rules": [{"toolName": "Bash", "ruleContent": "npm run test:e2e:*"}]}]}

plan = {**base, "hook_event_name": "PreToolUse", "tool_name": "ExitPlanMode", "tool_input": {"plan": "\n".join([
    "## Release 2.4", "", "1. Bump the version to **2.4.0** in `package.json`",
    "2. Update `CHANGELOG.md` from the merged pull requests", "3. Run unit, lint and end-to-end checks",
    "4. Tag `v2.4.0` and open the release pull request", "", "No production deploy in this plan."])}}


def ask_view(data, kind):
    suggestions = ask.always_rules(data, data["hook_event_name"]) or ()
    inp = data["tool_input"]
    return {"text": ask.message(data, kind, suggestions),
            "buttons": [t for t, _ in ask.buttons(kind, inp.get("questions") or [], bool(suggestions))]}


# tg-stop.py builds its ping inline in main(); these are the same calls in the same order.
stop_text = "Unit tests and lint pass. Deploy the release candidate to **staging** now, or wait for review?"
stop_lines = bot.header("Claude is waiting for you", repo, bot.read_transcript(transcript)["title"])
stop = {"text": "\n".join(stop_lines + [bot.cut(stop_text, bot.BODY_MAX), ""] + bot.reply_line()).strip(),
        "buttons": ["Answer in app"]}

views = {"question": ask_view(question, "question"), "permission": ask_view(permission, "permission"),
         "plan": ask_view(plan, "plan"), "stop": stop}
out = json.dumps(views, indent=1, ensure_ascii=False)
for leak in (repo, os.environ.get("HOME", "~"), "Reply in Claude"):
    assert leak not in out, f"unexpected text in mock data: {leak}"
assert "remote:acme-web/main" in out and "Terminal" in out
print("// Generated by docs/demo/render.sh from the plugin's message builders. Do not edit.")
print(f"window.MESSAGES = {out};")
